---
title: "Okuyasu Fan Club"
date: 2021-10-08
---
author: Matthew Perry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We love Part 4, specifically Okuysasu around these parts.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
